/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * OpenAPI spec version: 0.1.0
 */
export interface BodyImportIcsRouteEventsImportIcsPost {
  /** .ics файл для импорта */
  file: Blob
}

export interface CronSchema {
  date: string
  everyDay?: boolean
  everyWeek?: boolean
  everyMonth?: boolean
}

export interface EventAddTagRequest {
  tagIds: number[]
}

export interface EventAddUserRequest {
  userIds: number[]
}

export type EventCreateRequestDescription = string | null

export interface EventCreateRequest {
  title: string
  description?: EventCreateRequestDescription
  /** Тип события */
  type?: 'event'
  cron: CronSchema
  groupId: number
  duration?: number
  /** Упомянаемые пользователи */
  participantsIds?: number[]
  /** Привязанные теги */
  tagsIds?: number[]
  minutesBefore?: number[]
}

export type EventDetailsResponseDescription = string | null

export type EventDetailsResponseType =
  (typeof EventDetailsResponseType)[keyof typeof EventDetailsResponseType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventDetailsResponseType = {
  event: 'event',
  message: 'message',
} as const

export interface EventDetailsResponse {
  id: number
  title: string
  description?: EventDetailsResponseDescription
  cron: string
  isCycle: boolean
  type: EventDetailsResponseType
  creatorId: number
  group: GroupResponse
  tags: TagResponse[]
  notifies: EventNotifyResponse[]
  duration?: number
  eventHappened?: boolean
}

export interface EventNotifyResponse {
  minutesBefore: number
}

export type EventResponseDescription = string | null

export type EventResponseRespond = RespondResponse | null

export interface EventResponse {
  id: number
  title: string
  description?: EventResponseDescription
  cron: string
  isCycle: boolean
  type: string
  creatorId: number
  groupId: number
  duration?: number
  eventHappened?: boolean
  respond?: EventResponseRespond
  notifies?: number[]
}

export type EventUpdateRequestTitle = string | null

export type EventUpdateRequestDescription = string | null

export type EventUpdateRequestType = string | null

export type EventUpdateRequestCron = CronSchema | null

export type EventUpdateRequestDuration = number | null

export type EventUpdateRequestParticipantsIds = number[] | null

export type EventUpdateRequestTagsIds = number[] | null

export interface EventUpdateRequest {
  title?: EventUpdateRequestTitle
  description?: EventUpdateRequestDescription
  type?: EventUpdateRequestType
  cron?: EventUpdateRequestCron
  duration?: EventUpdateRequestDuration
  participantsIds?: EventUpdateRequestParticipantsIds
  tagsIds?: EventUpdateRequestTagsIds
}

export interface EventsResponse {
  events: EventResponse[]
}

export interface GetGroupResponse {
  group: GroupResponse
  role?: RoleResponse
}

export type GroupCreateRequestDescription = string | null

export interface GroupCreateRequest {
  name: string
  description?: GroupCreateRequestDescription
}

export interface GroupMemberResponse {
  userId: number
  groupId: number
  roleId: number
  notifyMode: NotifyMode
}

/**
 * Идентификатор роли
 */
export type GroupMemberUpdateRequestRoleId = number | null

/**
 * Список идентификаторов тегов
 */
export type GroupMemberUpdateRequestTags = number[] | null

export interface GroupMemberUpdateRequest {
  /** Идентификатор роли */
  roleId?: GroupMemberUpdateRequestRoleId
  /** Список идентификаторов тегов */
  tags?: GroupMemberUpdateRequestTags
}

export interface GroupNotifyModeRequest {
  notifyMode: NotifyMode
}

export type GroupResponseDescription = string | null

export interface GroupResponse {
  id: number
  name: string
  description?: GroupResponseDescription
}

export type GroupUpdateRequestDescription = string | null

export interface GroupUpdateRequest {
  name: string
  description?: GroupUpdateRequestDescription
}

export type GroupUserItemFirstName = string | null

export type GroupUserItemLastName = string | null

export type GroupUserItemPhone = string | null

export interface GroupUserItem {
  userId: number
  groupId: number
  role: RoleResponse
  maxId: number
  firstName?: GroupUserItemFirstName
  lastName?: GroupUserItemLastName
  phone?: GroupUserItemPhone
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface InviteCreateResponse {
  inviteKey: string
  inviteLink: string
}

export interface InviteGetResponse {
  inviteKey: string
  inviteLink: string
}

export type NotifyMode = (typeof NotifyMode)[keyof typeof NotifyMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotifyMode = {
  DEFAULT: 'DEFAULT',
  SILENT: 'SILENT',
  DISABLE: 'DISABLE',
} as const

export type PersonalGroupResponseDescription = string | null

export interface PersonalGroupResponse {
  id: number
  name: 'Личная'
  description?: PersonalGroupResponseDescription
}

export interface RespondResponse {
  id: number
  status: string
}

export type RoleResponseName =
  (typeof RoleResponseName)[keyof typeof RoleResponseName]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleResponseName = {
  Босс: 'Босс',
  Начальник: 'Начальник',
  Участник: 'Участник',
} as const

export interface RoleResponse {
  id: number
  name: RoleResponseName
}

export interface TagAssignRequest {
  userId: number
  tagId: number
}

export type TagCreateRequestDescription = string | null

export interface TagCreateRequest {
  name: string
  description?: TagCreateRequestDescription
  color: string
}

export type TagResponseDescription = string | null

export interface TagResponse {
  id: number
  groupId: number
  name: string
  description?: TagResponseDescription
  color: string
}

export type TagUpdateRequestName = string | null

export type TagUpdateRequestDescription = string | null

export type TagUpdateRequestColor = string | null

export interface TagUpdateRequest {
  name?: TagUpdateRequestName
  description?: TagUpdateRequestDescription
  color?: TagUpdateRequestColor
}

export type TagUserItemLastName = string | null

export type TagUserItemPhone = string | null

export interface TagUserItem {
  userId: number
  maxId: number
  firstName: string
  lastName?: TagUserItemLastName
  phone?: TagUserItemPhone
  roleId: number
}

export type UserGroupItemDescription = string | null

export interface UserGroupItem {
  groupId: number
  name: string
  description?: UserGroupItemDescription
  roleId: number
}

export interface UserGroupsResponse {
  groups: UserGroupItem[]
}

export type UserResponseMaxPhoto = string | null

export type UserResponseLastName = string | null

export type UserResponsePhone = string | null

export interface UserResponse {
  id: number
  maxId: number
  maxChatId: number
  maxPhoto?: UserResponseMaxPhoto
  firstName: string
  lastName?: UserResponseLastName
  phone?: UserResponsePhone
  timezone: number
  notifyMode: NotifyMode
}

export type UserUpdateRequestFirstName = string | null

export type UserUpdateRequestLastName = string | null

export type UserUpdateRequestPhoto = string | null

export type UserUpdateRequestPhone = string | null

export type UserUpdateRequestTimezone = number | null

export type UserUpdateRequestNotifyMode = NotifyMode | null

export interface UserUpdateRequest {
  firstName?: UserUpdateRequestFirstName
  lastName?: UserUpdateRequestLastName
  photo?: UserUpdateRequestPhoto
  phone?: UserUpdateRequestPhone
  timezone?: UserUpdateRequestTimezone
  notifyMode?: UserUpdateRequestNotifyMode
}

export type ValidationErrorLocItem = string | number

export interface ValidationError {
  loc: ValidationErrorLocItem[]
  msg: string
  type: string
}

export interface WebAppChat {
  id: number
  type: string
}

export type WebAppInitDataIp = string | null

export type WebAppInitDataQueryId = string | null

export type WebAppInitDataAuthDate = string | null

export type WebAppInitDataStartParam = string | null

export interface WebAppInitData {
  ip?: WebAppInitDataIp
  query_id?: WebAppInitDataQueryId
  chat: WebAppChat
  user: WebAppUser
  auth_date?: WebAppInitDataAuthDate
  hash: string
  start_param?: WebAppInitDataStartParam
}

export type WebAppUserLastName = string | null

export type WebAppUserUsername = string | null

export type WebAppUserLanguageCode = string | null

export type WebAppUserPhotoUrl = string | null

export interface WebAppUser {
  id: number
  first_name: string
  last_name?: WebAppUserLastName
  username?: WebAppUserUsername
  language_code?: WebAppUserLanguageCode
  photo_url?: WebAppUserPhotoUrl
}

export type CheckInitDataAuthGetParams = {
  WebAppData: string
}

export type ListPersonalEventsRouteUsersMeEventsGetParams = {
  /**
   * Список ID тегов через запятую для фильтрации
   */
  tag_ids?: string | null
}

export type ListUserEventsRouteUsersUserIdGroupsGroupIdEventsGetParams = {
  /**
   * Список ID тегов через запятую для фильтрации
   */
  tag_ids?: string | null
}

export type GetGroupEventsRouteEventsGroupsGroupIdGetParams = {
  /**
   * Список ID тегов через запятую для фильтрации
   */
  tag_ids?: string | null
}

export type GetUserEventsRouteEventsGetParams = {
  /**
   * Список ID тегов через запятую для фильтрации
   */
  tag_ids?: string | null
}
