/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
### Права доступа к сущностям

Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.

### Тестирование
Для тестирования запросов к API существует служебный токен (обладающий правами суперадминистратора), который можно сконфигурировать в
конфиг-переменной ``test_token``

 * OpenAPI spec version: 0.1.0
 */
export interface EventAddTagRequest {
  tagId: number;
}

export interface EventAddUserRequest {
  userId: number;
}

export type EventCreateRequestDescription = string | null;

export type EventCreateRequestGroupId = number | null;

export interface EventCreateRequest {
  title: string;
  description?: EventCreateRequestDescription;
  cron: string;
  isCycle: boolean;
  type: string;
  groupId?: EventCreateRequestGroupId;
}

export type EventResponseDescription = string | null;

export type EventResponseGroupId = number | null;

export interface EventResponse {
  id: number;
  title: string;
  description?: EventResponseDescription;
  cron: string;
  isCycle: boolean;
  type: string;
  creatorId: number;
  groupId?: EventResponseGroupId;
}

export type EventUpdateRequestTitle = string | null;

export type EventUpdateRequestDescription = string | null;

export type EventUpdateRequestCron = string | null;

export type EventUpdateRequestIsCycle = boolean | null;

export type EventUpdateRequestType = string | null;

export interface EventUpdateRequest {
  title?: EventUpdateRequestTitle;
  description?: EventUpdateRequestDescription;
  cron?: EventUpdateRequestCron;
  isCycle?: EventUpdateRequestIsCycle;
  type?: EventUpdateRequestType;
}

export interface EventsResponse {
  events: EventResponse[];
}

export type GroupCreateRequestDescription = string | null;

export interface GroupCreateRequest {
  name: string;
  description?: GroupCreateRequestDescription;
}

export interface GroupMemberAddRequest {
  inviteKey: string;
}

export interface GroupMemberResponse {
  userId: number;
  groupId: number;
  roleId: number;
}

export interface GroupMemberUpdateRequest {
  slaveId: number;
  groupId: number;
  newRoleId: number;
}

export type GroupResponseDescription = string | null;

export interface GroupResponse {
  id: number;
  name: string;
  description?: GroupResponseDescription;
}

export type GroupUpdateRequestName = string | null;

export type GroupUpdateRequestDescription = string | null;

export interface GroupUpdateRequest {
  name?: GroupUpdateRequestName;
  description?: GroupUpdateRequestDescription;
}

export type GroupUserItemLastName = string | null;

export interface GroupUserItem {
  userId: number;
  groupId: number;
  roleId: number;
  roleName: string;
  maxId: number;
  firstName: string;
  lastName?: GroupUserItemLastName;
  phone: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface InviteCreateRequest {
  expiresAt: string;
}

export interface InviteCreateResponse {
  inviteKey: string;
}

export interface TagAssignRequest {
  userId: number;
  tagId: number;
}

export interface TagAssignmentResponse {
  userId: number;
  tagId: number;
}

export type TagCreateRequestDescriptions = string | null;

export interface TagCreateRequest {
  name: string;
  descriptions?: TagCreateRequestDescriptions;
  color: string;
}

export type TagResponseDescriptions = string | null;

export interface TagResponse {
  id: number;
  groupId: number;
  name: string;
  descriptions?: TagResponseDescriptions;
  color: string;
}

export type TagUpdateRequestName = string | null;

export type TagUpdateRequestDescriptions = string | null;

export type TagUpdateRequestColor = string | null;

export interface TagUpdateRequest {
  name?: TagUpdateRequestName;
  descriptions?: TagUpdateRequestDescriptions;
  color?: TagUpdateRequestColor;
}

export type TagUserItemLastName = string | null;

export interface TagUserItem {
  userId: number;
  maxId: number;
  firstName: string;
  lastName?: TagUserItemLastName;
  phone: string;
  roleId: number;
}

export type UserCreateRequestLastName = string | null;

export type UserCreateRequestPhone = string | null;

export interface UserCreateRequest {
  maxId: number;
  maxChatId: number;
  firstName: string;
  lastName?: UserCreateRequestLastName;
  phone?: UserCreateRequestPhone;
}

export type UserGroupItemDescription = string | null;

export interface UserGroupItem {
  groupId: number;
  name: string;
  description?: UserGroupItemDescription;
  roleId: number;
}

export interface UserGroupsResponse {
  groups: UserGroupItem[];
}

export type UserResponseLastName = string | null;

export interface UserResponse {
  id: number;
  maxId: number;
  firstName: string;
  lastName?: UserResponseLastName;
  phone: string;
}

export type UserUpdateRequestFirstName = string | null;

export type UserUpdateRequestLastName = string | null;

export type UserUpdateRequestPhone = string | null;

export interface UserUpdateRequest {
  firstName?: UserUpdateRequestFirstName;
  lastName?: UserUpdateRequestLastName;
  phone?: UserUpdateRequestPhone;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

