/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
    ### Права доступа к сущностям
    
    Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
    набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.
    
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetGroupResponse,
  GroupCreateRequest,
  GroupMemberResponse,
  GroupMemberUpdateRequest,
  GroupNotifyModeRequest,
  GroupUpdateRequest,
  GroupUserItem,
  InviteCreateResponse,
  InviteGetResponse
} from '../gen.schemas';

import { request } from '.././client';
import type { BodyType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Создание группы. Может кто угодно.
 * @summary Create Group Route
 */
export const createGroupRouteGroupsPost = (
    groupCreateRequest: BodyType<GroupCreateRequest>,
 options?: SecondParameter<typeof request<GetGroupResponse>>,) => {
      return request<GetGroupResponse>(
      {url: `/groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: groupCreateRequest
    },
      options);
    }
  /**
 * Редактирование группы. Может только "Босс".
 * @summary Update Group Route
 */
export const updateGroupRouteGroupsGroupIdPatch = (
    groupId: number,
    groupUpdateRequest: BodyType<GroupUpdateRequest>,
 options?: SecondParameter<typeof request<GetGroupResponse>>,) => {
      return request<GetGroupResponse>(
      {url: `/groups/${groupId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: groupUpdateRequest
    },
      options);
    }
  /**
 * Получить группу. Могут только участники группы.
 * @summary Get Group
 */
export const getGroupGroupsGroupIdGet = (
    groupId: number,
 options?: SecondParameter<typeof request<GetGroupResponse>>,) => {
      return request<GetGroupResponse>(
      {url: `/groups/${groupId}`, method: 'GET'
    },
      options);
    }
  /**
 * Удалить группы. Может только "Босс".
 * @summary Delete Group Route
 */
export const deleteGroupRouteGroupsGroupIdDelete = (
    groupId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Смена роли юзера в группе. Может только "Босс".
 * @summary Update Group Membership Route
 */
export const updateGroupMembershipRouteGroupsGroupIdUsersSlaveIdPatch = (
    groupId: number,
    slaveId: number,
    groupMemberUpdateRequest: BodyType<GroupMemberUpdateRequest>,
 options?: SecondParameter<typeof request<GroupMemberResponse>>,) => {
      return request<GroupMemberResponse>(
      {url: `/groups/${groupId}/users/${slaveId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: groupMemberUpdateRequest
    },
      options);
    }
  /**
 * Удаление участника из группы.
"Босс" может удалить всех, "Начальник" не может удалить "Босса"
 * @summary Remove Group Member Route
 */
export const removeGroupMemberRouteGroupsGroupIdUsersSlaveIdDelete = (
    groupId: number,
    slaveId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}/users/${slaveId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Получить участника группы. Могут только участники группы.
 * @summary Get Group User Route
 */
export const getGroupUserRouteGroupsGroupIdUsersMemberIdGet = (
    groupId: number,
    memberId: number,
 options?: SecondParameter<typeof request<GroupUserItem>>,) => {
      return request<GroupUserItem>(
      {url: `/groups/${groupId}/users/${memberId}`, method: 'GET'
    },
      options);
    }
  /**
 * Получить всех пользователей группы. Могут только участники группы.
 * @summary List Group Users Route
 */
export const listGroupUsersRouteGroupsGroupIdUsersGet = (
    groupId: number,
 options?: SecondParameter<typeof request<GroupUserItem[]>>,) => {
      return request<GroupUserItem[]>(
      {url: `/groups/${groupId}/users`, method: 'GET'
    },
      options);
    }
  /**
 * Получит ссылку-приглашение в группу.
В группе может быть только одно активное приглашение.
 * @summary Get Invite Route
 */
export const getInviteRouteGroupsGroupIdInviteGet = (
    groupId: number,
 options?: SecondParameter<typeof request<InviteGetResponse>>,) => {
      return request<InviteGetResponse>(
      {url: `/groups/${groupId}/invite`, method: 'GET'
    },
      options);
    }
  /**
 * Создать (перевыпустить) приглашение в группу.
В группе может быть только одно активное приглашение.
 * @summary Create Invite Route
 */
export const createInviteRouteGroupsGroupIdInvitePost = (
    groupId: number,
 options?: SecondParameter<typeof request<InviteCreateResponse>>,) => {
      return request<InviteCreateResponse>(
      {url: `/groups/${groupId}/invite`, method: 'POST'
    },
      options);
    }
  /**
 * Удалить приглашение в группу.
В группе может быть только одно активное приглашение, поэтому удалится оно.
 * @summary Delete Invite Route
 */
export const deleteInviteRouteGroupsGroupIdInviteDelete = (
    groupId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}/invite`, method: 'DELETE'
    },
      options);
    }
  /**
 * Изменить режим уведомлений в группе для самого себя.
 * @summary Update Group Notify Mode
 */
export const updateGroupNotifyModeGroupsGroupIdNotifyPatch = (
    groupId: number,
    groupNotifyModeRequest: BodyType<GroupNotifyModeRequest>,
 options?: SecondParameter<typeof request<GroupMemberResponse>>,) => {
      return request<GroupMemberResponse>(
      {url: `/groups/${groupId}/notify`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: groupNotifyModeRequest
    },
      options);
    }
  export type CreateGroupRouteGroupsPostResult = NonNullable<Awaited<ReturnType<typeof createGroupRouteGroupsPost>>>
export type UpdateGroupRouteGroupsGroupIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateGroupRouteGroupsGroupIdPatch>>>
export type GetGroupGroupsGroupIdGetResult = NonNullable<Awaited<ReturnType<typeof getGroupGroupsGroupIdGet>>>
export type DeleteGroupRouteGroupsGroupIdDeleteResult = NonNullable<Awaited<ReturnType<typeof deleteGroupRouteGroupsGroupIdDelete>>>
export type UpdateGroupMembershipRouteGroupsGroupIdUsersSlaveIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateGroupMembershipRouteGroupsGroupIdUsersSlaveIdPatch>>>
export type RemoveGroupMemberRouteGroupsGroupIdUsersSlaveIdDeleteResult = NonNullable<Awaited<ReturnType<typeof removeGroupMemberRouteGroupsGroupIdUsersSlaveIdDelete>>>
export type GetGroupUserRouteGroupsGroupIdUsersMemberIdGetResult = NonNullable<Awaited<ReturnType<typeof getGroupUserRouteGroupsGroupIdUsersMemberIdGet>>>
export type ListGroupUsersRouteGroupsGroupIdUsersGetResult = NonNullable<Awaited<ReturnType<typeof listGroupUsersRouteGroupsGroupIdUsersGet>>>
export type GetInviteRouteGroupsGroupIdInviteGetResult = NonNullable<Awaited<ReturnType<typeof getInviteRouteGroupsGroupIdInviteGet>>>
export type CreateInviteRouteGroupsGroupIdInvitePostResult = NonNullable<Awaited<ReturnType<typeof createInviteRouteGroupsGroupIdInvitePost>>>
export type DeleteInviteRouteGroupsGroupIdInviteDeleteResult = NonNullable<Awaited<ReturnType<typeof deleteInviteRouteGroupsGroupIdInviteDelete>>>
export type UpdateGroupNotifyModeGroupsGroupIdNotifyPatchResult = NonNullable<Awaited<ReturnType<typeof updateGroupNotifyModeGroupsGroupIdNotifyPatch>>>
