/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
### Права доступа к сущностям

Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.

### Тестирование
Для тестирования запросов к API существует служебный токен (обладающий правами суперадминистратора), который можно сконфигурировать в
конфиг-переменной ``test_token``

 * OpenAPI spec version: 0.1.0
 */
import type {
  GroupCreateRequest,
  GroupMemberAddRequest,
  GroupMemberResponse,
  GroupMemberUpdateRequest,
  GroupResponse,
  GroupUpdateRequest,
  GroupUserItem,
  InviteCreateRequest,
  InviteCreateResponse
} from '../gen.schemas';

import { request } from '.././client';
import type { BodyType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Создание группы
 * @summary Create Group Route
 */
export const createGroupRouteGroupsPost = (
    groupCreateRequest: BodyType<GroupCreateRequest>,
 options?: SecondParameter<typeof request<GroupResponse>>,) => {
      return request<GroupResponse>(
      {url: `/groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: groupCreateRequest
    },
      options);
    }
  /**
 * Редактирование группы (только создатель)
 * @summary Update Group Route
 */
export const updateGroupRouteGroupsGroupIdPatch = (
    groupId: number,
    groupUpdateRequest: BodyType<GroupUpdateRequest>,
 options?: SecondParameter<typeof request<GroupResponse>>,) => {
      return request<GroupResponse>(
      {url: `/groups/${groupId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: groupUpdateRequest
    },
      options);
    }
  /**
 * Получить группу по идентификатору
 * @summary Get Group
 */
export const getGroupGroupsGroupIdGet = (
    groupId: number,
 options?: SecondParameter<typeof request<GroupResponse>>,) => {
      return request<GroupResponse>(
      {url: `/groups/${groupId}`, method: 'GET'
    },
      options);
    }
  /**
 * Удаление группы (только администратор)
 * @summary Delete Group Route
 */
export const deleteGroupRouteGroupsGroupIdDelete = (
    groupId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Редактирование связи пользователя и группы
 * @summary Update Group Membership
 */
export const updateGroupMembershipGroupsGroupIdUsersSlaveIdPatch = (
    groupId: number,
    slaveId: number,
    groupMemberUpdateRequest: BodyType<GroupMemberUpdateRequest>,
 options?: SecondParameter<typeof request<GroupMemberResponse>>,) => {
      return request<GroupMemberResponse>(
      {url: `/groups/${groupId}/users/${slaveId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: groupMemberUpdateRequest
    },
      options);
    }
  /**
 * Удаление участника из группы
 * @summary Remove Group Member Route
 */
export const removeGroupMemberRouteGroupsGroupIdUsersSlaveIdDelete = (
    groupId: number,
    slaveId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}/users/${slaveId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Получить участника группы по идентификатору
 * @summary Get Group User Route
 */
export const getGroupUserRouteGroupsGroupIdUsersMemberIdGet = (
    groupId: number,
    memberId: number,
 options?: SecondParameter<typeof request<GroupUserItem>>,) => {
      return request<GroupUserItem>(
      {url: `/groups/${groupId}/users/${memberId}`, method: 'GET'
    },
      options);
    }
  /**
 * Получить список всех пользователей группы
 * @summary List Group Users Route
 */
export const listGroupUsersRouteGroupsGroupIdUsersGet = (
    groupId: number,
 options?: SecondParameter<typeof request<GroupUserItem[]>>,) => {
      return request<GroupUserItem[]>(
      {url: `/groups/${groupId}/users`, method: 'GET'
    },
      options);
    }
  /**
 * Создание приглашения в группу
 * @summary Create Invite Route
 */
export const createInviteRouteGroupsGroupIdInvitePost = (
    groupId: number,
    inviteCreateRequest: BodyType<InviteCreateRequest>,
 options?: SecondParameter<typeof request<InviteCreateResponse>>,) => {
      return request<InviteCreateResponse>(
      {url: `/groups/${groupId}/invite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inviteCreateRequest
    },
      options);
    }
  /**
 * Добавление пользователя в группу
 * @summary Join Group
 */
export const joinGroupGroupsJoinPost = (
    groupMemberAddRequest: BodyType<GroupMemberAddRequest>,
 options?: SecondParameter<typeof request<GroupMemberResponse>>,) => {
      return request<GroupMemberResponse>(
      {url: `/groups/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: groupMemberAddRequest
    },
      options);
    }
  export type CreateGroupRouteGroupsPostResult = NonNullable<Awaited<ReturnType<typeof createGroupRouteGroupsPost>>>
export type UpdateGroupRouteGroupsGroupIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateGroupRouteGroupsGroupIdPatch>>>
export type GetGroupGroupsGroupIdGetResult = NonNullable<Awaited<ReturnType<typeof getGroupGroupsGroupIdGet>>>
export type DeleteGroupRouteGroupsGroupIdDeleteResult = NonNullable<Awaited<ReturnType<typeof deleteGroupRouteGroupsGroupIdDelete>>>
export type UpdateGroupMembershipGroupsGroupIdUsersSlaveIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateGroupMembershipGroupsGroupIdUsersSlaveIdPatch>>>
export type RemoveGroupMemberRouteGroupsGroupIdUsersSlaveIdDeleteResult = NonNullable<Awaited<ReturnType<typeof removeGroupMemberRouteGroupsGroupIdUsersSlaveIdDelete>>>
export type GetGroupUserRouteGroupsGroupIdUsersMemberIdGetResult = NonNullable<Awaited<ReturnType<typeof getGroupUserRouteGroupsGroupIdUsersMemberIdGet>>>
export type ListGroupUsersRouteGroupsGroupIdUsersGetResult = NonNullable<Awaited<ReturnType<typeof listGroupUsersRouteGroupsGroupIdUsersGet>>>
export type CreateInviteRouteGroupsGroupIdInvitePostResult = NonNullable<Awaited<ReturnType<typeof createInviteRouteGroupsGroupIdInvitePost>>>
export type JoinGroupGroupsJoinPostResult = NonNullable<Awaited<ReturnType<typeof joinGroupGroupsJoinPost>>>
