/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * OpenAPI spec version: 0.1.0
 */
import { request } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Проверка соединения
 * @summary Check Connection
 */
export const checkConnectionHealthGet = (
    
 options?: SecondParameter<typeof request<unknown>>,) => {
      return request<unknown>(
      {url: `/health`, method: 'GET'
    },
      options);
    }
  export type CheckConnectionHealthGetResult = NonNullable<Awaited<ReturnType<typeof checkConnectionHealthGet>>>
