/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
### Права доступа к сущностям

Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.

 * OpenAPI spec version: 0.1.0
 */
import { request } from '.././client'
import type {
  TagAssignRequest,
  TagCreateRequest,
  TagResponse,
  TagUpdateRequest,
  TagUserItem,
} from '../gen.schemas'

import type { BodyType } from '.././client'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Создать тег. Могут только "Босс" и "Начальник".
 * @summary Create Tag Route
 */
export const createTagRouteGroupsGroupIdTagsPost = (
  groupId: number,
  tagCreateRequest: BodyType<TagCreateRequest>,
  options?: SecondParameter<typeof request<TagResponse>>,
) => {
  return request<TagResponse>(
    {
      url: `/groups/${groupId}/tags`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tagCreateRequest,
    },
    options,
  )
}
/**
 * Получить все теги группы. Могут только участники группы.
 * @summary List Group Tags Route
 */
export const listGroupTagsRouteGroupsGroupIdTagsGet = (
  groupId: number,
  options?: SecondParameter<typeof request<Array<TagResponse>>>,
) => {
  return request<Array<TagResponse>>(
    { url: `/groups/${groupId}/tags`, method: 'GET' },
    options,
  )
}
/**
 * Редактировать тег. Могут только "Босс" и "Начальник".
 * @summary Update Tag Route
 */
export const updateTagRouteGroupsGroupIdTagsTagIdPatch = (
  groupId: number,
  tagId: number,
  tagUpdateRequest: BodyType<TagUpdateRequest>,
  options?: SecondParameter<typeof request<TagResponse>>,
) => {
  return request<TagResponse>(
    {
      url: `/groups/${groupId}/tags/${tagId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: tagUpdateRequest,
    },
    options,
  )
}
/**
 * Удалить тег. Могут только "Босс" и "Начальник".
 * @summary Delete Tag Route
 */
export const deleteTagRouteGroupsGroupIdTagsTagIdDelete = (
  groupId: number,
  tagId: number,
  options?: SecondParameter<typeof request<void>>,
) => {
  return request<void>(
    { url: `/groups/${groupId}/tags/${tagId}`, method: 'DELETE' },
    options,
  )
}
/**
 * Добавить (назначить, привязать) тег пользователю.
Могут только "Босс" и "Начальник".
 * @summary Assign Tag To User Route
 */
export const assignTagToUserRouteGroupsGroupIdTagsUsersPost = (
  groupId: number,
  tagAssignRequest: BodyType<TagAssignRequest>,
  options?: SecondParameter<typeof request<void>>,
) => {
  return request<void>(
    {
      url: `/groups/${groupId}/tags/users`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tagAssignRequest,
    },
    options,
  )
}
/**
 * Удалить (отвязать) тег у пользователя.
Могут только "Босс" и "Начальник".
 * @summary Remove Tag From User Route
 */
export const removeTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDelete = (
  groupId: number,
  userId: number,
  tagId: number,
  options?: SecondParameter<typeof request<void>>,
) => {
  return request<void>(
    {
      url: `/groups/${groupId}/tags/users/${userId}/${tagId}`,
      method: 'DELETE',
    },
    options,
  )
}
/**
 * Получить список пользователей, у которых есть тег.
Могут только участники группы.
 * @summary List Tag Users Route
 */
export const listTagUsersRouteGroupsGroupIdTagsTagIdUsersGet = (
  groupId: number,
  tagId: number,
  options?: SecondParameter<typeof request<Array<TagUserItem>>>,
) => {
  return request<Array<TagUserItem>>(
    { url: `/groups/${groupId}/tags/${tagId}/users`, method: 'GET' },
    options,
  )
}
export type CreateTagRouteGroupsGroupIdTagsPostResult = NonNullable<
  Awaited<ReturnType<typeof createTagRouteGroupsGroupIdTagsPost>>
>
export type ListGroupTagsRouteGroupsGroupIdTagsGetResult = NonNullable<
  Awaited<ReturnType<typeof listGroupTagsRouteGroupsGroupIdTagsGet>>
>
export type UpdateTagRouteGroupsGroupIdTagsTagIdPatchResult = NonNullable<
  Awaited<ReturnType<typeof updateTagRouteGroupsGroupIdTagsTagIdPatch>>
>
export type DeleteTagRouteGroupsGroupIdTagsTagIdDeleteResult = NonNullable<
  Awaited<ReturnType<typeof deleteTagRouteGroupsGroupIdTagsTagIdDelete>>
>
export type AssignTagToUserRouteGroupsGroupIdTagsUsersPostResult = NonNullable<
  Awaited<ReturnType<typeof assignTagToUserRouteGroupsGroupIdTagsUsersPost>>
>
export type RemoveTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDeleteResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof removeTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDelete
      >
    >
  >
export type ListTagUsersRouteGroupsGroupIdTagsTagIdUsersGetResult = NonNullable<
  Awaited<ReturnType<typeof listTagUsersRouteGroupsGroupIdTagsTagIdUsersGet>>
>
