/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
### Права доступа к сущностям

Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.

### Тестирование
Для тестирования запросов к API существует служебный токен (обладающий правами суперадминистратора), который можно сконфигурировать в
конфиг-переменной ``test_token``

 * OpenAPI spec version: 0.1.0
 */
import type {
  DeleteTagRouteGroupsGroupIdTagsTagIdDeleteParams,
  GroupTagsResponse,
  ListGroupTagsRouteGroupsGroupIdTagsGetParams,
  ListTagUsersRouteGroupsGroupIdTagsTagIdUsersGetParams,
  RemoveTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDeleteParams,
  TagAssignRequest,
  TagAssignmentResponse,
  TagCreateRequest,
  TagResponse,
  TagUpdateRequest,
  TagUsersResponse
} from '../gen.schemas';

import { request } from '.././client';
import type { BodyType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Создание тега
 * @summary Create Tag Route
 */
export const createTagRouteGroupsGroupIdTagsPost = (
    groupId: number,
    tagCreateRequest: BodyType<TagCreateRequest>,
 options?: SecondParameter<typeof request<TagResponse>>,) => {
      return request<TagResponse>(
      {url: `/groups/${groupId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tagCreateRequest
    },
      options);
    }
  /**
 * Получить список тегов группы
 * @summary List Group Tags Route
 */
export const listGroupTagsRouteGroupsGroupIdTagsGet = (
    groupId: number,
    params: ListGroupTagsRouteGroupsGroupIdTagsGetParams,
 options?: SecondParameter<typeof request<GroupTagsResponse>>,) => {
      return request<GroupTagsResponse>(
      {url: `/groups/${groupId}/tags`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Редактирование тега
 * @summary Update Tag Route
 */
export const updateTagRouteGroupsGroupIdTagsTagIdPatch = (
    groupId: number,
    tagId: number,
    tagUpdateRequest: BodyType<TagUpdateRequest>,
 options?: SecondParameter<typeof request<TagResponse>>,) => {
      return request<TagResponse>(
      {url: `/groups/${groupId}/tags/${tagId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: tagUpdateRequest
    },
      options);
    }
  /**
 * Удаление тега
 * @summary Delete Tag Route
 */
export const deleteTagRouteGroupsGroupIdTagsTagIdDelete = (
    groupId: number,
    tagId: number,
    params: DeleteTagRouteGroupsGroupIdTagsTagIdDeleteParams,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}/tags/${tagId}`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * Назначить тег пользователю
 * @summary Assign Tag To User Route
 */
export const assignTagToUserRouteGroupsGroupIdTagsUsersPost = (
    groupId: number,
    tagAssignRequest: BodyType<TagAssignRequest>,
 options?: SecondParameter<typeof request<TagAssignmentResponse>>,) => {
      return request<TagAssignmentResponse>(
      {url: `/groups/${groupId}/tags/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tagAssignRequest
    },
      options);
    }
  /**
 * Удалить тег у пользователя
 * @summary Remove Tag From User Route
 */
export const removeTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDelete = (
    groupId: number,
    userId: number,
    tagId: number,
    params: RemoveTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDeleteParams,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/groups/${groupId}/tags/users/${userId}/${tagId}`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * Получить список пользователей, у которых назначен тег
 * @summary List Tag Users Route
 */
export const listTagUsersRouteGroupsGroupIdTagsTagIdUsersGet = (
    groupId: number,
    tagId: number,
    params: ListTagUsersRouteGroupsGroupIdTagsTagIdUsersGetParams,
 options?: SecondParameter<typeof request<TagUsersResponse>>,) => {
      return request<TagUsersResponse>(
      {url: `/groups/${groupId}/tags/${tagId}/users`, method: 'GET',
        params
    },
      options);
    }
  export type CreateTagRouteGroupsGroupIdTagsPostResult = NonNullable<Awaited<ReturnType<typeof createTagRouteGroupsGroupIdTagsPost>>>
export type ListGroupTagsRouteGroupsGroupIdTagsGetResult = NonNullable<Awaited<ReturnType<typeof listGroupTagsRouteGroupsGroupIdTagsGet>>>
export type UpdateTagRouteGroupsGroupIdTagsTagIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateTagRouteGroupsGroupIdTagsTagIdPatch>>>
export type DeleteTagRouteGroupsGroupIdTagsTagIdDeleteResult = NonNullable<Awaited<ReturnType<typeof deleteTagRouteGroupsGroupIdTagsTagIdDelete>>>
export type AssignTagToUserRouteGroupsGroupIdTagsUsersPostResult = NonNullable<Awaited<ReturnType<typeof assignTagToUserRouteGroupsGroupIdTagsUsersPost>>>
export type RemoveTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDeleteResult = NonNullable<Awaited<ReturnType<typeof removeTagFromUserRouteGroupsGroupIdTagsUsersUserIdTagIdDelete>>>
export type ListTagUsersRouteGroupsGroupIdTagsTagIdUsersGetResult = NonNullable<Awaited<ReturnType<typeof listTagUsersRouteGroupsGroupIdTagsTagIdUsersGet>>>
