/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
### Права доступа к сущностям

Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.

### Тестирование
Для тестирования запросов к API существует служебный токен (обладающий правами суперадминистратора), который можно сконфигурировать в
конфиг-переменной ``test_token``

 * OpenAPI spec version: 0.1.0
 */
import type {
  DeleteEventRouteEventsEventIdDeleteParams,
  EventAddTagRequest,
  EventAddUserRequest,
  EventCreateRequest,
  EventResponse,
  EventUpdateRequest,
  EventsResponse,
  GetEventRouteEventsEventIdGetParams,
  GetGroupEventsRouteEventsGroupsGroupIdGetParams,
  GetOtherUserEventsRouteEventsUsersTargetUserIdEventsGetParams
} from '../gen.schemas';

import { request } from '.././client';
import type { BodyType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Добавить тег для события (может только 1 и 2 роль)
 * @summary Add Tag To Event Route
 */
export const addTagToEventRouteEventsEventIdTagsPost = (
    eventId: number,
    eventAddTagRequest: BodyType<EventAddTagRequest>,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/${eventId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventAddTagRequest
    },
      options);
    }
  /**
 * Получить событие
 * @summary Get Event Route
 */
export const getEventRouteEventsEventIdGet = (
    eventId: number,
    params: GetEventRouteEventsEventIdGetParams,
 options?: SecondParameter<typeof request<EventResponse>>,) => {
      return request<EventResponse>(
      {url: `/events/${eventId}`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Редактирование события (может только 1 и 2 роль)
 * @summary Update Event Route
 */
export const updateEventRouteEventsEventIdPatch = (
    eventId: number,
    eventUpdateRequest: BodyType<EventUpdateRequest>,
 options?: SecondParameter<typeof request<EventResponse>>,) => {
      return request<EventResponse>(
      {url: `/events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: eventUpdateRequest
    },
      options);
    }
  /**
 * Удаление события (может только 1 и 2 роль)
 * @summary Delete Event Route
 */
export const deleteEventRouteEventsEventIdDelete = (
    eventId: number,
    params: DeleteEventRouteEventsEventIdDeleteParams,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/${eventId}`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * Создание события (может только 1 и 2 роль)
 * @summary Create Event Route
 */
export const createEventRouteEventsPost = (
    eventCreateRequest: BodyType<EventCreateRequest>,
 options?: SecondParameter<typeof request<EventResponse>>,) => {
      return request<EventResponse>(
      {url: `/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventCreateRequest
    },
      options);
    }
  /**
 * Добавить пользователя для события (может только 1 и 2 роль)
 * @summary Add User To Event Route
 */
export const addUserToEventRouteEventsEventIdUsersPost = (
    eventId: number,
    eventAddUserRequest: BodyType<EventAddUserRequest>,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/${eventId}/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventAddUserRequest
    },
      options);
    }
  /**
 * Просмотр всех событий группы (может только пользователь находящийся в этой группе)
 * @summary Get Group Events Route
 */
export const getGroupEventsRouteEventsGroupsGroupIdGet = (
    groupId: number,
    params: GetGroupEventsRouteEventsGroupsGroupIdGetParams,
 options?: SecondParameter<typeof request<EventsResponse>>,) => {
      return request<EventsResponse>(
      {url: `/events/groups/${groupId}`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Просмотр всех своих событий
 * @summary Get User Events Route
 */
export const getUserEventsRouteEventsUsersUserIdGet = (
    userId: number,
 options?: SecondParameter<typeof request<EventsResponse>>,) => {
      return request<EventsResponse>(
      {url: `/events/users/${userId}`, method: 'GET'
    },
      options);
    }
  /**
 * Просмотр событий другого пользователя (Если вы в одной группе)
 * @summary Get Other User Events Route
 */
export const getOtherUserEventsRouteEventsUsersTargetUserIdEventsGet = (
    targetUserId: number,
    params: GetOtherUserEventsRouteEventsUsersTargetUserIdEventsGetParams,
 options?: SecondParameter<typeof request<EventsResponse>>,) => {
      return request<EventsResponse>(
      {url: `/events/users/${targetUserId}/events`, method: 'GET',
        params
    },
      options);
    }
  export type AddTagToEventRouteEventsEventIdTagsPostResult = NonNullable<Awaited<ReturnType<typeof addTagToEventRouteEventsEventIdTagsPost>>>
export type GetEventRouteEventsEventIdGetResult = NonNullable<Awaited<ReturnType<typeof getEventRouteEventsEventIdGet>>>
export type UpdateEventRouteEventsEventIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateEventRouteEventsEventIdPatch>>>
export type DeleteEventRouteEventsEventIdDeleteResult = NonNullable<Awaited<ReturnType<typeof deleteEventRouteEventsEventIdDelete>>>
export type CreateEventRouteEventsPostResult = NonNullable<Awaited<ReturnType<typeof createEventRouteEventsPost>>>
export type AddUserToEventRouteEventsEventIdUsersPostResult = NonNullable<Awaited<ReturnType<typeof addUserToEventRouteEventsEventIdUsersPost>>>
export type GetGroupEventsRouteEventsGroupsGroupIdGetResult = NonNullable<Awaited<ReturnType<typeof getGroupEventsRouteEventsGroupsGroupIdGet>>>
export type GetUserEventsRouteEventsUsersUserIdGetResult = NonNullable<Awaited<ReturnType<typeof getUserEventsRouteEventsUsersUserIdGet>>>
export type GetOtherUserEventsRouteEventsUsersTargetUserIdEventsGetResult = NonNullable<Awaited<ReturnType<typeof getOtherUserEventsRouteEventsUsersTargetUserIdEventsGet>>>
