/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
    ### Права доступа к сущностям
    
    Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
    набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.
    
 * OpenAPI spec version: 0.1.0
 */
import type {
  BodyImportIcsRouteEventsImportIcsPost,
  EventAddTagRequest,
  EventAddUserRequest,
  EventCreateRequest,
  EventDetailsResponse,
  EventResponse,
  EventUpdateRequest,
  EventsResponse,
  GetGroupEventsRouteEventsGroupsGroupIdGetParams,
  GetUserEventsRouteEventsGetParams
} from '../gen.schemas';

import { request } from '.././client';
import type { BodyType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Создать событие (встреча или сообщение) в группе.
Могут только "Босс" и "Начальник".
 * @summary Create Event Route
 */
export const createEventRouteEventsPost = (
    eventCreateRequest: BodyType<EventCreateRequest>,
 options?: SecondParameter<typeof request<EventResponse>>,) => {
      return request<EventResponse>(
      {url: `/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventCreateRequest
    },
      options);
    }
  /**
 * Добавить тег для события. Могут только "Босс" и "Начальник".
 * @summary Add Tag To Event Route
 */
export const addTagToEventRouteEventsEventIdTagsPost = (
    eventId: number,
    eventAddTagRequest: BodyType<EventAddTagRequest>,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/${eventId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventAddTagRequest
    },
      options);
    }
  /**
 * Получить событие. Могут только участники события.
 * @summary Get Event Route
 */
export const getEventRouteEventsEventIdGet = (
    eventId: number,
 options?: SecondParameter<typeof request<EventDetailsResponse>>,) => {
      return request<EventDetailsResponse>(
      {url: `/events/${eventId}`, method: 'GET'
    },
      options);
    }
  /**
 * Редактировать событие. Могут только "Босс" и "Начальник".
 * @summary Update Event Route
 */
export const updateEventRouteEventsEventIdPatch = (
    eventId: number,
    eventUpdateRequest: BodyType<EventUpdateRequest>,
 options?: SecondParameter<typeof request<EventResponse>>,) => {
      return request<EventResponse>(
      {url: `/events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: eventUpdateRequest
    },
      options);
    }
  /**
 * Удалить событие. Могут только "Босс" и "Начальник".
 * @summary Delete Event Route
 */
export const deleteEventRouteEventsEventIdDelete = (
    eventId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/${eventId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Добавить (привязать) пользователя в событие.
Могут только "Босс" и "Начальник".
 * @summary Add User To Event Route
 */
export const addUserToEventRouteEventsEventIdUsersPost = (
    eventId: number,
    eventAddUserRequest: BodyType<EventAddUserRequest>,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/${eventId}/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventAddUserRequest
    },
      options);
    }
  /**
 * Просмотр всех событий группы, в которых пользователь принимает участие
 * @summary Get Group Events Route
 */
export const getGroupEventsRouteEventsGroupsGroupIdGet = (
    groupId: number,
    params?: GetGroupEventsRouteEventsGroupsGroupIdGetParams,
 options?: SecondParameter<typeof request<EventsResponse>>,) => {
      return request<EventsResponse>(
      {url: `/events/groups/${groupId}`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Просмотр всех своих событий во всех группах.
 * @summary Get User Events Route
 */
export const getUserEventsRouteEventsGet = (
    params?: GetUserEventsRouteEventsGetParams,
 options?: SecondParameter<typeof request<EventsResponse>>,) => {
      return request<EventsResponse>(
      {url: `/events/`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Импортировать события из .ics файла в личную группу пользователя
 * @summary Import Ics Route
 */
export const importIcsRouteEventsImportIcsPost = (
    bodyImportIcsRouteEventsImportIcsPost: BodyType<BodyImportIcsRouteEventsImportIcsPost>,
 options?: SecondParameter<typeof request<EventsResponse>>,) => {const formData = new FormData();
formData.append(`file`, bodyImportIcsRouteEventsImportIcsPost.file)

      return request<EventsResponse>(
      {url: `/events/import/ics`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  /**
 * Выгрузить все события группы, в которых участвует пользователь, во всех группах
 * @summary Export User Events All Groups Route
 */
export const exportUserEventsAllGroupsRouteEventsExportAllGroupsGet = (
    
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/export/all-groups`, method: 'GET'
    },
      options);
    }
  /**
 * Выгрузить все события пользователя в рамках одной группы
 * @summary Export User Events In Group Route
 */
export const exportUserEventsInGroupRouteEventsExportGroupsGroupIdUserGet = (
    groupId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/export/groups/${groupId}/user`, method: 'GET'
    },
      options);
    }
  /**
 * Выгрузить все события группы (только для ролей 1 и 2)
 * @summary Export All Group Events Route
 */
export const exportAllGroupEventsRouteEventsExportGroupsGroupIdAllGet = (
    groupId: number,
 options?: SecondParameter<typeof request<void>>,) => {
      return request<void>(
      {url: `/events/export/groups/${groupId}/all`, method: 'GET'
    },
      options);
    }
  export type CreateEventRouteEventsPostResult = NonNullable<Awaited<ReturnType<typeof createEventRouteEventsPost>>>
export type AddTagToEventRouteEventsEventIdTagsPostResult = NonNullable<Awaited<ReturnType<typeof addTagToEventRouteEventsEventIdTagsPost>>>
export type GetEventRouteEventsEventIdGetResult = NonNullable<Awaited<ReturnType<typeof getEventRouteEventsEventIdGet>>>
export type UpdateEventRouteEventsEventIdPatchResult = NonNullable<Awaited<ReturnType<typeof updateEventRouteEventsEventIdPatch>>>
export type DeleteEventRouteEventsEventIdDeleteResult = NonNullable<Awaited<ReturnType<typeof deleteEventRouteEventsEventIdDelete>>>
export type AddUserToEventRouteEventsEventIdUsersPostResult = NonNullable<Awaited<ReturnType<typeof addUserToEventRouteEventsEventIdUsersPost>>>
export type GetGroupEventsRouteEventsGroupsGroupIdGetResult = NonNullable<Awaited<ReturnType<typeof getGroupEventsRouteEventsGroupsGroupIdGet>>>
export type GetUserEventsRouteEventsGetResult = NonNullable<Awaited<ReturnType<typeof getUserEventsRouteEventsGet>>>
export type ImportIcsRouteEventsImportIcsPostResult = NonNullable<Awaited<ReturnType<typeof importIcsRouteEventsImportIcsPost>>>
export type ExportUserEventsAllGroupsRouteEventsExportAllGroupsGetResult = NonNullable<Awaited<ReturnType<typeof exportUserEventsAllGroupsRouteEventsExportAllGroupsGet>>>
export type ExportUserEventsInGroupRouteEventsExportGroupsGroupIdUserGetResult = NonNullable<Awaited<ReturnType<typeof exportUserEventsInGroupRouteEventsExportGroupsGroupIdUserGet>>>
export type ExportAllGroupEventsRouteEventsExportGroupsGroupIdAllGetResult = NonNullable<Awaited<ReturnType<typeof exportAllGroupEventsRouteEventsExportGroupsGroupIdAllGet>>>
