/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
    ### Права доступа к сущностям
    
    Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
    набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.
    
 * OpenAPI spec version: 0.1.0
 */
import type {
  EventResponse,
  ListPersonalEventsRouteUsersMeEventsGetParams,
  ListUserEventsRouteUsersUserIdGroupsGroupIdEventsGetParams,
  PersonalGroupResponse,
  TagResponse,
  UserGroupsResponse,
  UserResponse,
  UserUpdateRequest
} from '../gen.schemas';

import { request } from '.././client';
import type { BodyType } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Получить пользователя. Можно только самого себя.
 * @summary Get User By Id Route
 */
export const getUserByIdRouteUsersMeGet = (
    
 options?: SecondParameter<typeof request<UserResponse>>,) => {
      return request<UserResponse>(
      {url: `/users/me`, method: 'GET'
    },
      options);
    }
  /**
 * Редактировать пользователя. Можно только самого себя.
 * @summary Update User Route
 */
export const updateUserRouteUsersPatch = (
    userUpdateRequest: BodyType<UserUpdateRequest>,
 options?: SecondParameter<typeof request<UserResponse>>,) => {
      return request<UserResponse>(
      {url: `/users/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateRequest
    },
      options);
    }
  /**
 * Получить персональную группу пользователя.
 * @summary Get Personal Group Route
 */
export const getPersonalGroupRouteUsersMeGroupsPersonalGet = (
    
 options?: SecondParameter<typeof request<PersonalGroupResponse>>,) => {
      return request<PersonalGroupResponse>(
      {url: `/users/me/groups/personal`, method: 'GET'
    },
      options);
    }
  /**
 * Получить список групп, в которых состоит пользователь. Можно только свои группы.
 * @summary List User Groups Route
 */
export const listUserGroupsRouteUsersMeGroupsGet = (
    
 options?: SecondParameter<typeof request<UserGroupsResponse>>,) => {
      return request<UserGroupsResponse>(
      {url: `/users/me/groups`, method: 'GET'
    },
      options);
    }
  /**
 * @summary List Personal Events Route
 */
export const listPersonalEventsRouteUsersMeEventsGet = (
    params?: ListPersonalEventsRouteUsersMeEventsGetParams,
 options?: SecondParameter<typeof request<EventResponse[]>>,) => {
      return request<EventResponse[]>(
      {url: `/users/me/events`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Получить список тегов пользователя в рамках группы
 * @summary List User Tags Route
 */
export const listUserTagsRouteUsersUserIdGroupsGroupIdTagsGet = (
    userId: number,
    groupId: number,
 options?: SecondParameter<typeof request<TagResponse[]>>,) => {
      return request<TagResponse[]>(
      {url: `/users/${userId}/groups/${groupId}/tags`, method: 'GET'
    },
      options);
    }
  /**
 * Получить список событий пользователя в рамках группы
 * @summary List User Events Route
 */
export const listUserEventsRouteUsersUserIdGroupsGroupIdEventsGet = (
    userId: number,
    groupId: number,
    params?: ListUserEventsRouteUsersUserIdGroupsGroupIdEventsGetParams,
 options?: SecondParameter<typeof request<EventResponse[]>>,) => {
      return request<EventResponse[]>(
      {url: `/users/${userId}/groups/${groupId}/events`, method: 'GET',
        params
    },
      options);
    }
  export type GetUserByIdRouteUsersMeGetResult = NonNullable<Awaited<ReturnType<typeof getUserByIdRouteUsersMeGet>>>
export type UpdateUserRouteUsersPatchResult = NonNullable<Awaited<ReturnType<typeof updateUserRouteUsersPatch>>>
export type GetPersonalGroupRouteUsersMeGroupsPersonalGetResult = NonNullable<Awaited<ReturnType<typeof getPersonalGroupRouteUsersMeGroupsPersonalGet>>>
export type ListUserGroupsRouteUsersMeGroupsGetResult = NonNullable<Awaited<ReturnType<typeof listUserGroupsRouteUsersMeGroupsGet>>>
export type ListPersonalEventsRouteUsersMeEventsGetResult = NonNullable<Awaited<ReturnType<typeof listPersonalEventsRouteUsersMeEventsGet>>>
export type ListUserTagsRouteUsersUserIdGroupsGroupIdTagsGetResult = NonNullable<Awaited<ReturnType<typeof listUserTagsRouteUsersUserIdGroupsGroupIdTagsGet>>>
export type ListUserEventsRouteUsersUserIdGroupsGroupIdEventsGetResult = NonNullable<Awaited<ReturnType<typeof listUserEventsRouteUsersUserIdGroupsGroupIdEventsGet>>>
