/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsCreateRouteImport } from './routes/groups/create'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdSettingsRouteImport } from './routes/groups/$groupId/settings'
import { Route as GroupsGroupIdMembersIndexRouteImport } from './routes/groups/$groupId/members/index'
import { Route as GroupsGroupIdMembersMemberIdRouteImport } from './routes/groups/$groupId/members/$memberId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSettingsRoute = GroupsGroupIdSettingsRouteImport.update({
  id: '/groups/$groupId/settings',
  path: '/groups/$groupId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersIndexRoute =
  GroupsGroupIdMembersIndexRouteImport.update({
    id: '/groups/$groupId/members/',
    path: '/groups/$groupId/members/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdMembersMemberIdRoute =
  GroupsGroupIdMembersMemberIdRouteImport.update({
    id: '/groups/$groupId/members/$memberId',
    path: '/groups/$groupId/members/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/events/$id': typeof EventsIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/events/$id': typeof EventsIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/events/$id': typeof EventsIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/members/': typeof GroupsGroupIdMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/events/$id'
    | '/groups/create'
    | '/groups/$groupId/settings'
    | '/groups/$groupId'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/events/$id'
    | '/groups/create'
    | '/groups/$groupId/settings'
    | '/groups/$groupId'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/members'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/events/$id'
    | '/groups/create'
    | '/groups/$groupId/settings'
    | '/groups/$groupId/'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  EventsIdRoute: typeof EventsIdRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsGroupIdSettingsRoute: typeof GroupsGroupIdSettingsRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdMembersMemberIdRoute: typeof GroupsGroupIdMembersMemberIdRoute
  GroupsGroupIdMembersIndexRoute: typeof GroupsGroupIdMembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/settings': {
      id: '/groups/$groupId/settings'
      path: '/groups/$groupId/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof GroupsGroupIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/members/': {
      id: '/groups/$groupId/members/'
      path: '/groups/$groupId/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/members/$memberId': {
      id: '/groups/$groupId/members/$memberId'
      path: '/groups/$groupId/members/$memberId'
      fullPath: '/groups/$groupId/members/$memberId'
      preLoaderRoute: typeof GroupsGroupIdMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  EventsIdRoute: EventsIdRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsGroupIdSettingsRoute: GroupsGroupIdSettingsRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdMembersMemberIdRoute: GroupsGroupIdMembersMemberIdRoute,
  GroupsGroupIdMembersIndexRoute: GroupsGroupIdMembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
