/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsCreateRouteImport } from './routes/groups/create'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdSettingsRouteImport } from './routes/groups/$groupId/settings'
import { Route as GroupsGroupIdSearchRouteImport } from './routes/groups/$groupId/search'
import { Route as GroupsGroupIdMembersIndexRouteImport } from './routes/groups/$groupId/members/index'
import { Route as GroupsGroupIdTagsCreateRouteImport } from './routes/groups/$groupId/tags/create'
import { Route as GroupsGroupIdMembersMemberIdRouteImport } from './routes/groups/$groupId/members/$memberId'
import { Route as GroupsGroupIdEventsCreateRouteImport } from './routes/groups/$groupId/events/create'
import { Route as GroupsGroupIdEventsEventIdRouteImport } from './routes/groups/$groupId/events/$eventId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSettingsRoute = GroupsGroupIdSettingsRouteImport.update({
  id: '/groups/$groupId/settings',
  path: '/groups/$groupId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSearchRoute = GroupsGroupIdSearchRouteImport.update({
  id: '/groups/$groupId/search',
  path: '/groups/$groupId/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersIndexRoute =
  GroupsGroupIdMembersIndexRouteImport.update({
    id: '/groups/$groupId/members/',
    path: '/groups/$groupId/members/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdTagsCreateRoute = GroupsGroupIdTagsCreateRouteImport.update({
  id: '/groups/$groupId/tags/create',
  path: '/groups/$groupId/tags/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersMemberIdRoute =
  GroupsGroupIdMembersMemberIdRouteImport.update({
    id: '/groups/$groupId/members/$memberId',
    path: '/groups/$groupId/members/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdEventsCreateRoute =
  GroupsGroupIdEventsCreateRouteImport.update({
    id: '/groups/$groupId/events/create',
    path: '/groups/$groupId/events/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdEventsEventIdRoute =
  GroupsGroupIdEventsEventIdRouteImport.update({
    id: '/groups/$groupId/events/$eventId',
    path: '/groups/$groupId/events/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/events/$id': typeof EventsIdRoute
  '/events/create': typeof EventsCreateRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/$groupId/search': typeof GroupsGroupIdSearchRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/events/$eventId': typeof GroupsGroupIdEventsEventIdRoute
  '/groups/$groupId/events/create': typeof GroupsGroupIdEventsCreateRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/tags/create': typeof GroupsGroupIdTagsCreateRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/events/$id': typeof EventsIdRoute
  '/events/create': typeof EventsCreateRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/$groupId/search': typeof GroupsGroupIdSearchRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/events/$eventId': typeof GroupsGroupIdEventsEventIdRoute
  '/groups/$groupId/events/create': typeof GroupsGroupIdEventsCreateRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/tags/create': typeof GroupsGroupIdTagsCreateRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/events/$id': typeof EventsIdRoute
  '/events/create': typeof EventsCreateRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/$groupId/search': typeof GroupsGroupIdSearchRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/events/$eventId': typeof GroupsGroupIdEventsEventIdRoute
  '/groups/$groupId/events/create': typeof GroupsGroupIdEventsCreateRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/tags/create': typeof GroupsGroupIdTagsCreateRoute
  '/groups/$groupId/members/': typeof GroupsGroupIdMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/search'
    | '/settings'
    | '/events/$id'
    | '/events/create'
    | '/groups/create'
    | '/groups/$groupId/search'
    | '/groups/$groupId/settings'
    | '/groups/$groupId'
    | '/groups/$groupId/events/$eventId'
    | '/groups/$groupId/events/create'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/tags/create'
    | '/groups/$groupId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/search'
    | '/settings'
    | '/events/$id'
    | '/events/create'
    | '/groups/create'
    | '/groups/$groupId/search'
    | '/groups/$groupId/settings'
    | '/groups/$groupId'
    | '/groups/$groupId/events/$eventId'
    | '/groups/$groupId/events/create'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/tags/create'
    | '/groups/$groupId/members'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/search'
    | '/settings'
    | '/events/$id'
    | '/events/create'
    | '/groups/create'
    | '/groups/$groupId/search'
    | '/groups/$groupId/settings'
    | '/groups/$groupId/'
    | '/groups/$groupId/events/$eventId'
    | '/groups/$groupId/events/create'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/tags/create'
    | '/groups/$groupId/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsCreateRoute: typeof EventsCreateRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsGroupIdSearchRoute: typeof GroupsGroupIdSearchRoute
  GroupsGroupIdSettingsRoute: typeof GroupsGroupIdSettingsRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdEventsEventIdRoute: typeof GroupsGroupIdEventsEventIdRoute
  GroupsGroupIdEventsCreateRoute: typeof GroupsGroupIdEventsCreateRoute
  GroupsGroupIdMembersMemberIdRoute: typeof GroupsGroupIdMembersMemberIdRoute
  GroupsGroupIdTagsCreateRoute: typeof GroupsGroupIdTagsCreateRoute
  GroupsGroupIdMembersIndexRoute: typeof GroupsGroupIdMembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/settings': {
      id: '/groups/$groupId/settings'
      path: '/groups/$groupId/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof GroupsGroupIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/search': {
      id: '/groups/$groupId/search'
      path: '/groups/$groupId/search'
      fullPath: '/groups/$groupId/search'
      preLoaderRoute: typeof GroupsGroupIdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/members/': {
      id: '/groups/$groupId/members/'
      path: '/groups/$groupId/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/tags/create': {
      id: '/groups/$groupId/tags/create'
      path: '/groups/$groupId/tags/create'
      fullPath: '/groups/$groupId/tags/create'
      preLoaderRoute: typeof GroupsGroupIdTagsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/members/$memberId': {
      id: '/groups/$groupId/members/$memberId'
      path: '/groups/$groupId/members/$memberId'
      fullPath: '/groups/$groupId/members/$memberId'
      preLoaderRoute: typeof GroupsGroupIdMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/events/create': {
      id: '/groups/$groupId/events/create'
      path: '/groups/$groupId/events/create'
      fullPath: '/groups/$groupId/events/create'
      preLoaderRoute: typeof GroupsGroupIdEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/events/$eventId': {
      id: '/groups/$groupId/events/$eventId'
      path: '/groups/$groupId/events/$eventId'
      fullPath: '/groups/$groupId/events/$eventId'
      preLoaderRoute: typeof GroupsGroupIdEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  EventsIdRoute: EventsIdRoute,
  EventsCreateRoute: EventsCreateRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsGroupIdSearchRoute: GroupsGroupIdSearchRoute,
  GroupsGroupIdSettingsRoute: GroupsGroupIdSettingsRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdEventsEventIdRoute: GroupsGroupIdEventsEventIdRoute,
  GroupsGroupIdEventsCreateRoute: GroupsGroupIdEventsCreateRoute,
  GroupsGroupIdMembersMemberIdRoute: GroupsGroupIdMembersMemberIdRoute,
  GroupsGroupIdTagsCreateRoute: GroupsGroupIdTagsCreateRoute,
  GroupsGroupIdMembersIndexRoute: GroupsGroupIdMembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
