"""change EventModel

Revision ID: 2025.11.12_18.56
Revises: 2025.11.12_19.16
Create Date: 2025-11-12 23:56:29.213409

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.12_18.56"
down_revision: str | None = "2025.11.12_19.16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("event_happened", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "event_happened")
    # ### end Alembic commands ###
