"""short_users

Revision ID: 2025.11.07_05.25
Revises: 2025.11.07_04.54
Create Date: 2025-11-07 05:25:44.012912

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.07_05.25"
down_revision: str | None = "2025.11.07_04.54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("max_id", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("fullname", sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f("uq_users_max_id"), "users", ["max_id"])
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(op.f("uq_users_max_id"), "users", type_="unique")
    op.drop_column("users", "fullname")
    op.drop_column("users", "max_id")
    # ### end Alembic commands ###
