"""users_photo

Revision ID: 2025.11.13_14.30
Revises: 2025.11.13_13.53
Create Date: 2025-11-13 17:30:59.013624

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.13_14.30"
down_revision: str | None = "2025.11.13_13.53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("max_photo", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "max_photo")
    # ### end Alembic commands ###
