"""change users

Revision ID: 2025.11.07_12.07
Revises: 2025.11.07_05.26
Create Date: 2025-11-07 14:07:49.276226

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.07_12.07"
down_revision: str | None = "2025.11.07_05.26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("first_name", sa.String(length=64), nullable=False),
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=64), nullable=True))
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.drop_column("users", "username")
    op.drop_column("users", "fullname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "fullname",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "username",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        op.f("uq_users_username"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=True,
    )
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(length=16),
        nullable=True,
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
