"""change EventModel

Revision ID: 2025.11.14_19.50
Revises: 2025.11.13_20.36
Create Date: 2025-11-15 00:50:01.016273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025.11.14_19.50'
down_revision: Union[str, None] = '2025.11.13_20.36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration', sa.Integer(),))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'duration')
    # ### end Alembic commands ###
