"""invite_key

Revision ID: 2025.11.09_08.49
Revises: 2025.11.09_06.44
Create Date: 2025-11-09 08:49:25.893466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.09_08.49"
down_revision: str | None = "2025.11.09_06.44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invites", sa.Column("key", sa.String(length=16), nullable=False))
    op.drop_constraint(op.f("uq_invites_link"), "invites", type_="unique")
    op.create_unique_constraint(op.f("uq_invites_key"), "invites", ["key"])
    op.drop_column("invites", "link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invites",
        sa.Column("link", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_invites_key"), "invites", type_="unique")
    op.create_unique_constraint(
        op.f("uq_invites_link"),
        "invites",
        ["link"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("invites", "key")
    # ### end Alembic commands ###
