"""roles

Revision ID: 2025.11.07_05.26
Revises: 2025.11.07_05.25
Create Date: 2025-11-07 05:26:12.768726

"""

from collections.abc import Sequence

from alembic import op

from maxhack.core.role.ids import (
    CREATOR_ROLE_ID,
    CREATOR_ROLE_NAME,
    EDITOR_ROLE_ID,
    EDITOR_ROLE_NAME,
    MEMBER_ROLE_ID,
    MEMBER_ROLE_NAME,
)

# revision identifiers, used by Alembic.
revision: str = "2025.11.07_05.26"
down_revision: str | None = "2025.11.07_05.25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""INSERT INTO roles (id, name) VALUES
        ({CREATOR_ROLE_ID}, '{CREATOR_ROLE_NAME}'),
        ({EDITOR_ROLE_ID}, '{EDITOR_ROLE_NAME}'),
        ({MEMBER_ROLE_ID}, '{MEMBER_ROLE_NAME}')
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM roles")
    # ### end Alembic commands ###
