"""m2m_soft

Revision ID: 2025.11.15_00.28
Revises: 2025.11.14_19.50
Create Date: 2025-11-15 03:28:52.418823

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.15_00.28"
down_revision: str | None = "2025.11.14_19.50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "duration", existing_type=sa.INTEGER(), nullable=False)

    op.add_column(
        "tags_to_events",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            primary_key=True,
        ),
    )
    op.execute("ALTER TABLE tags_to_events DROP CONSTRAINT pk_tags_to_events CASCADE")

    op.create_primary_key(op.f("pk_tags_to_events"), "tags_to_events", ["id"])
    op.create_index(
        op.f("ix_tags_to_events_tag_id"),
        "tags_to_events",
        ["tag_id", "event_id"],
        unique=True,
        postgresql_where="tags_to_events.deleted_at IS NULL",
    )

    op.add_column(
        "users_to_events",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            primary_key=True,
        ),
    )
    op.execute("ALTER TABLE users_to_events DROP CONSTRAINT pk_users_to_events CASCADE")
    op.create_primary_key(op.f("pk_users_to_events"), "users_to_events", ["id"])
    op.create_index(
        op.f("ix_users_to_events_user_id"),
        "users_to_events",
        ["user_id", "event_id"],
        unique=True,
        postgresql_where="users_to_events.deleted_at IS NULL",
    )

    op.add_column(
        "users_to_groups",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            primary_key=True,
        ),
    )
    op.execute("ALTER TABLE users_to_groups DROP CONSTRAINT pk_users_to_groups CASCADE")
    op.create_primary_key(op.f("pk_users_to_groups"), "users_to_groups", ["id"])
    op.create_index(
        op.f("ix_users_to_groups_user_id"),
        "users_to_groups",
        ["user_id", "group_id"],
        unique=True,
        postgresql_where="users_to_groups.deleted_at IS NULL",
    )

    op.add_column(
        "users_to_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.execute("ALTER TABLE users_to_tags DROP CONSTRAINT pk_users_to_tags CASCADE")
    op.create_primary_key(op.f("pk_users_to_tags"), "users_to_tags", ["id"])
    op.create_index(
        op.f("ix_users_to_tags_user_id"),
        "users_to_tags",
        ["user_id", "tag_id"],
        unique=True,
        postgresql_where="users_to_tags.deleted_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_users_to_tags_user_id"),
        table_name="users_to_tags",
        postgresql_where="users_to_tags.deleted_at IS NULL",
    )
    op.execute("ALTER TABLE users_to_tags DROP CONSTRAINT pk_users_to_tags CASCADE")
    op.drop_column("users_to_tags", "id")
    op.create_primary_key(
        op.f("pk_users_to_tags"),
        "users_to_tags",
        ["user_id", "tag_id"],
    )

    op.drop_index(
        op.f("ix_users_to_groups_user_id"),
        table_name="users_to_groups",
        postgresql_where="users_to_groups.deleted_at IS NULL",
    )
    op.execute("ALTER TABLE users_to_groups DROP CONSTRAINT pk_users_to_groups CASCADE")
    op.drop_column("users_to_groups", "id")
    op.create_primary_key(
        op.f("pk_users_to_groups"),
        "users_to_groups",
        ["user_id", "group_id"],
    )

    op.drop_index(
        op.f("ix_users_to_events_user_id"),
        table_name="users_to_events",
        postgresql_where="users_to_events.deleted_at IS NULL",
    )
    op.execute("ALTER TABLE users_to_events DROP CONSTRAINT pk_users_to_events CASCADE")
    op.drop_column("users_to_events", "id")
    op.create_primary_key(
        op.f("pk_users_to_events"),
        "users_to_events",
        ["user_id", "event_id"],
    )

    op.drop_index(
        op.f("ix_tags_to_events_tag_id"),
        table_name="tags_to_events",
        postgresql_where="tags_to_events.deleted_at IS NULL",
    )
    op.execute("ALTER TABLE tags_to_events DROP CONSTRAINT pk_tags_to_events CASCADE")
    op.drop_column("tags_to_events", "id")
    op.create_primary_key(
        op.f("pk_tags_to_events"),
        "tags_to_events",
        ["tag_id", "event_id"],
    )

    op.alter_column("events", "duration", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
