"""max_chat_id

Revision ID: 2025.11.09_06.44
Revises: 2025.11.08_13.41
Create Date: 2025-11-09 06:44:32.901787

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.09_06.44"
down_revision: str | None = "2025.11.08_13.41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("max_chat_id", sa.Integer(), nullable=False))
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(length=16),
        nullable=True,
    )
    op.create_unique_constraint(op.f("uq_users_max_chat_id"), "users", ["max_chat_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_max_chat_id"), "users", type_="unique")
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
    )
    op.drop_column("users", "max_chat_id")
    # ### end Alembic commands ###
