"""invites

Revision ID: 2025.11.07_04.54
Revises: 2025.11.05_21.50
Create Date: 2025-11-07 04:54:26.685322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2025.11.07_04.54"
down_revision: str | None = "2025.11.05_21.50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_to_invites")
    op.add_column(
        "users_to_groups",
        sa.Column("invite_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_users_to_groups_invite_id_invites"),
        "users_to_groups",
        "invites",
        ["invite_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_to_groups_invite_id_invites"),
        "users_to_groups",
        type_="foreignkey",
    )
    op.drop_column("users_to_groups", "invite_id")
    op.create_table(
        "users_to_invites",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("invite_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('UTC'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('UTC'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["invites.id"],
            name=op.f("fk_users_to_invites_invite_id_invites"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_to_invites_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "invite_id",
            name=op.f("pk_users_to_invites"),
        ),
    )
    # ### end Alembic commands ###
