"""change Events

Revision ID: 2025.11.08_13.41
Revises: 2025.11.07_12.07
Create Date: 2025-11-08 15:41:58.205399

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.08_13.41"
down_revision: str | None = "2025.11.07_12.07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "group_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "group_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
