"""notify_mode

Revision ID: 2025.11.13_20.36
Revises: 2025.11.13_14.30
Create Date: 2025-11-13 23:36:35.269675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.13_20.36"
down_revision: str | None = "2025.11.13_14.30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("notify_mode", sa.String(length=16), nullable=False),
    )
    op.add_column(
        "users_to_groups",
        sa.Column("notify_mode", sa.String(length=16), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_to_groups", "notify_mode")
    op.drop_column("users", "notify_mode")
    # ### end Alembic commands ###
