/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * OpenAPI spec version: 0.1.0
 */
import type {
  CheckInitDataAuthGetParams,
  WebAppInitData
} from '../gen.schemas';

import { request } from '.././client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Валидация WebAppData из MAX
 * @summary Check Init Data
 */
export const checkInitDataAuthGet = (
    params: CheckInitDataAuthGetParams,
 options?: SecondParameter<typeof request<WebAppInitData>>,) => {
      return request<WebAppInitData>(
      {url: `/auth`, method: 'GET',
        params
    },
      options);
    }
  export type CheckInitDataAuthGetResult = NonNullable<Awaited<ReturnType<typeof checkInitDataAuthGet>>>
