/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Таск трекер для МАКС
 * 
### Права доступа к сущностям

Для каждой сущности предусмотрен определённый набор прав, которые, в зависимости от логики, могут назначаться различному
набору ролей. Также, помимо основного набора прав, ограничения могут быть выставлены непосредственно на уровне определённых ролей.

 * OpenAPI spec version: 0.1.0
 */
import { request } from '.././client'
import type { CheckInitDataAuthGetParams, WebAppInitData } from '../gen.schemas'


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Валидация WebAppData из MAX
 * @summary Check Init Data
 */
export const checkInitDataAuthGet = (
  params: CheckInitDataAuthGetParams,
  options?: SecondParameter<typeof request<WebAppInitData>>,
) => {
  return request<WebAppInitData>(
    { url: `/auth`, method: 'GET', params },
    options,
  )
}
export type CheckInitDataAuthGetResult = NonNullable<
  Awaited<ReturnType<typeof checkInitDataAuthGet>>
>
